easy_admin:
    list:
        title: 'list.%%entity_label%%'
        max_results: 10
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    site_name: 'Instagram.'
    user:
        display_name: true
        display_avatar: true
        name_property_path: 'fullName'
        avatar_property_path: 'gravatar'
    design:
        assets:
            favicon: '/assets/images/favicon.ico'
    entities:
#        # List the entity class name you want to manage
      User:
        class: App\Entity\User
        list:
            label: 'Users'
            title: "Most recent users"
            fields: 
              - { property: 'imageName', type: 'image', label: 'Avatar', base_path: '%app.path.profile_image%' }
              - { property: 'username', label: 'Username'}
              - { property: 'fullname', label: 'Name'}
              - { property: 'phone', label: 'Phone number' }
              - { property: 'email', label: 'E-mail' }
        form:
          fields:
            - username
            - email
            - enabled
            - lastLogin
            # if administrators are allowed to edit users' passwords and roles, add this:
            - { property: 'plainPassword', type: 'text', type_options: { required: false } }
            - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

      Post:
        class: App\Entity\Post
