vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        post_file:
            uri_prefix: '%app.path.post_file%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_file%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        profile_image:
            uri_prefix: '%app.path.profile_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.profile_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
